---
commitizen:
  bump_map:
    BREAKING CHANGE: MAJOR
    break: MAJOR
    build: null
    chore: null
    ci: null
    docs: null
    feat: MINOR
    fix: PATCH
    perf: PATCH
    refactor: PATCH
    style: null
    test: null
  bump_message: "bump: version $current_version \u2192 $new_version"
  change_type_map:
    bug fix: Fix
    build: Build
    chore: Chore
    ci: CI
    docs: Docs
    feature: Feat
    fix: Fix
    perf: Perf
    refactor: Refactor
    style: Style
    test: Test
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.1.3
  version_files:
  - .cz.yaml
  - ./meta/main.yml
  version_scheme: semver
