---
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Create security sources list
  become: yes
  shell: grep security /etc/apt/sources.list | tee /etc/apt/sources_security_only.list
  register: security_sources

- name: Upgrade security packages with the newly created file
  become: yes
  command: apt-get upgrade -y -o Dir::Etc::SourceList=/etc/apt/sources_security_only.list
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: security_sources.stdout != ""

- name: Check if reboot is required
  become: yes
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Set reboot required fact
  set_fact:
    reboot_is_required: "{{ reboot_required_file.stat.exists }}"

- name: Notify about reboot requirement
  debug:
    msg: "Reboot is required for {{ inventory_hostname }}"
  when: reboot_is_required

- name: Notify that no reboot is required
  debug:
    msg: "No reboot is required for {{ inventory_hostname }}"
  when: not reboot_is_required
