name: Bump and Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.cz.yaml'
      - 'CHANGELOG.md'
      - 'README.md'
      - '.gitignore'
jobs:
  bump-version:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    permissions: write-all # Needed for automatic release
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - name: Create bump and changelog
        # This step will add an environment variable REVISION with the new version
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: echo new version
        run: |
          echo "$REVISION"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
