name: Publish to Ansible Galaxy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and Ansible Galaxy CLI
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Import role to Ansible Galaxy
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          ansible-galaxy import ${{ github.repository_owner }} ${REPO_NAME} --token ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
