name: Publish to Ansible Galaxy

on:
  release:
    types: [created]

env:
  ANSIBLE_GALAXY_NAME: security_patching
  ANSIBLE_GALAXY_NAMESPACE: ngochieu642

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and Ansible Galaxy CLI
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Import role to Ansible Galaxy
        run: |
          ansible-galaxy role import \
            --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} \
            ${{ env.ANSIBLE_GALAXY_NAMESPACE }} \
            ${{ env.ANSIBLE_GALAXY_NAME }}
